Included images in MarkDownView parsing to allow pop up modal for lar…
uwindsorcss/css-site pull request #50
Opened 2024-09-17 15:22 UTC by SyndicateGit

…ger image.

Before Image Click:
![image](https://github.com/user-attachments/assets/77c7abb4-a443-4e13-8279-86d4be00696f)
After:
![image](https://github.com/user-attachments/assets/dd1e96ee-7d45-4042-ac6e-0ea8c737bb57)

### What are you trying to accomplish?

Make images able to open a modal on click to allow users to see smaller images more clearly. 

### How are you accomplishing it?
It wasn't as easy for MarkdownView because the img elements needs to be parsed and MarkdownView is in server side which required me to not have useStates in that file. Otherwise, HTML's new dialog element would've made it much easier. 

Keep server side MarkdownView the same, have it parse img: --> to client side component ImageModal to handle the modal logic. Unfortunately memo() had problems with hydration that I couldn't figure out a fix nor understand why.

### Is there anything reviewers should know?

- [x] Is it safe to rollback this change if anything goes wrong?

2024-09-17 22:13 UTC, BorhanSaflo requested changes
The image modal looks great!

I've noticed one issue where images in posts are not rendering. For example, if you navigate to the last page (page 7) of the News tab, the images are are not rendering.

2024-09-17 23:40 UTC, SyndicateGit commented
New to the dev environment. How would I test adding images to news posts in dev mode? I see it's fetching from postgress and there are tables for it. Would I have to insert rows or there an easier way? 
![image](https://github.com/user-attachments/assets/5e5cf446-7866-4585-98ba-e454160d7f8d)

2024-09-17 23:46 UTC, BorhanSaflo commented
Currently, images are just URLs in Markdown, and the MarkdownView component renders these images directly from those URLs. They are not stored in the database. This is something we plan on changing (#44).

2024-09-18 14:02 UTC, SyndicateGit commented
Is there a way for me to access the mockup of the posts? I'm having difficulty testing if it works on the markup when I don't know how the Markup is formatted differently between the about page markup and the news / events post markup.

2024-09-23 01:57 UTC, SyndicateGit commented
I think I was able to fix it by changing next image to regular html img, tested with image markup. Could this get vercel deployed again?

2024-09-27 01:33 UTC, SyndicateGit commented
![image](https://github.com/user-attachments/assets/eb1d653c-0729-47be-affc-f9a0cdd502c4)
It works now. Problem before is I was using Next Image optimization but these photos are markdown src so are fetched dynamically. I changed it to regular img html.

2024-09-28 01:40 UTC, BorhanSaflo approved these changes
LGTM, great job!

2024-09-28 01:40 UTC, merged